# Generated by Django 5.1.6 on 2025-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='img',
            field=models.URLField(default='https://e7.pngegg.com/pngimages/448/676/png-clipart-tamil-cuisine-south-indian-cuisine-rajwadi-veg-restaurant-egmore-vegetarian-cuisine-south-indian-food-food-breakfast-thumbnail.png'),
        ),
    ]
