# Generated by Django 5.1.6 on 2025-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.URLField(default='https://www.freepnglogos.com/uploads/dominos-png-logo/starting-dominos-pizza-franchise-png-logo-3.png'),
        ),
    ]
