# Generated by Django 5.1.6 on 2025-03-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='delivery.menu'),
        ),
    ]
